-- Query Spark SQL que define o domínio de CDBs com resgate (CRES) a clonar.
-- Contrato: retornar somente uma coluna chamada NUM_IF, sem valores nulos.
-- Use RAW_<TABELA> entre chaves duplas para referenciar uma fonte RAW.
-- filtros num_tipo_if 49 e cod_cond_resgate  mercado,com tabela e especifica e tipo escalonamento nulo

WITH FILTRO_BASE AS (
    SELECT DISTINCT IFE.NUM_IF
    FROM {{RAW_INSTRUMENTO_FINANCEIRO}} IFE
        INNER JOIN {{RAW_TITULO}} TIT
            ON TIT.NUM_IF = IFE.NUM_IF
        INNER JOIN {{RAW_CONDICAO_IF}} CIF
            ON CIF.NUM_IF = IFE.NUM_IF
        INNER JOIN {{RAW_RESGATE}} RES
            ON RES.NUM_CONDICAO_IF = CIF.NUM_CONDICAO_IF
    WHERE IFE.NUM_TIPO_IF = 49
        AND RES.COD_COND_RESGATE IN (
            'MERCADO',
            'COM TABELA',
            'ESPECIFICA'
        )
        AND TIT.COD_TIPO_ESCALONAMENTO IS NULL
        AND IFE.DAT_EXCLUSAO IS NULL
        AND CIF.DAT_EXCLUSAO IS NULL
        AND RES.DAT_EXCLUSAO IS NULL
),
FLAGS_IF AS (
    SELECT DISTINCT C.NUM_IF
    FROM {{RAW_CONDICAO_IF}} C
        INNER JOIN FILTRO_BASE FB
            ON FB.NUM_IF = C.NUM_IF
    WHERE C.DAT_EXCLUSAO IS NULL
        AND C.COD_TIPO_CONDICAO_IF <> 20
),
DEP_IF AS (
    SELECT DISTINCT DP.NUM_IF
    FROM {{RAW_DEPOSITO_AUTOMATICO_IF}} DP
        INNER JOIN FILTRO_BASE FB
            ON FB.NUM_IF = DP.NUM_IF
    WHERE DP.NUM_IF IS NOT NULL
)
SELECT DISTINCT F.NUM_IF
FROM FLAGS_IF F
    INNER JOIN DEP_IF DEP
        ON DEP.NUM_IF = F.NUM_IF
    INNER JOIN {{RAW_OPERACAO}} O
        ON O.NUM_IF = F.NUM_IF
    INNER JOIN {{RAW_DADO_OPERACAO}} DOP
        ON DOP.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN {{RAW_LANCAMENTO}} LAN
        ON LAN.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN {{RAW_ESPECIFICACAO}} ESP
        ON ESP.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN {{RAW_ESPECIFICACAO_COMITENTE}} EPC
        ON EPC.NUM_ID_ESPECIFICACAO = ESP.NUM_ID_ESPECIFICACAO;
