SELECT SUM(CASE WHEN CR.VAL_PERCENTUAL IS NULL THEN 1 ELSE 0 END) AS PCT_NULO,
       COUNT(*) AS TOTAL,
       SUM(CASE WHEN CR.IND_EXCLUIDO IS NULL THEN 1 ELSE 0 END) AS IND_NULO
  FROM CETIP.CONDICAO_RESGATE CR
  JOIN CETIP.RESGATE R ON R.NUM_CONDICAO_IF = CR.NUM_CONDICAO_IF
  JOIN CETIP.CONDICAO_IF C ON C.NUM_CONDICAO_IF = R.NUM_CONDICAO_IF
 WHERE C.NUM_IF IN (<lote>) AND C.DAT_EXCLUSAO IS NULL
   AND TRIM(UPPER(R.COD_COND_RESGATE)) = 'COM TABELA';
