-Valida lastro e lci n tem dependencia
SELECT COUNT(DISTINCT SCR.NUM_IF) FROM CETIP.CREDITO_SCR SCR
  JOIN CETIP.INSTRUMENTO_FINANCEIRO I ON I.NUM_IF = SCR.NUM_IF
 WHERE I.NUM_TIPO_IF = 81 AND SCR.DAT_EXCLUSAO IS NULL AND I.DAT_EXCLUSAO IS NULL;  -- LCI+lastro

SELECT COUNT(DISTINCT CDC.NUM_IF) FROM CETIP.CREDITO_DC CDC
  JOIN CETIP.INSTRUMENTO_FINANCEIRO I ON I.NUM_IF = CDC.NUM_IF
 WHERE I.NUM_TIPO_IF = 96 AND CDC.DAT_EXCLUSAO IS NULL AND I.DAT_EXCLUSAO IS NULL;  -- LCA+DC

SELECT NUM_TIPO_IF, COUNT(*) FROM CETIP.INSTRUMENTO_FINANCEIRO
 WHERE NUM_TIPO_IF IN (81,96) AND DAT_EXCLUSAO IS NULL GROUP BY NUM_TIPO_IF;        -- sanidade


-tenta ver dependencia
  SELECT SCR.NUM_TIPO_IF, COUNT(*) linhas, COUNT(DISTINCT SCR.NUM_IF) instrumentos
FROM CETIP.CREDITO_SCR SCR WHERE SCR.DAT_EXCLUSAO IS NULL
GROUP BY SCR.NUM_TIPO_IF ORDER BY 2 DESC;

SELECT CDC.NUM_TIPO_IF, COUNT(*) linhas, COUNT(DISTINCT CDC.NUM_IF) instrumentos
FROM CETIP.CREDITO_DC CDC WHERE CDC.DAT_EXCLUSAO IS NULL
GROUP BY CDC.NUM_TIPO_IF ORDER BY 2 DESC;



-- 1) A tabela tem coluna NUM_IF? (o spec só declara NUM_IF_PERTENCE)
SELECT column_name, data_type, nullable FROM all_tab_columns
WHERE owner='CETIP' AND table_name='HISTORICO_IF_TITULO' AND column_name LIKE '%NUM_IF%'
ORDER BY column_name;

-- 2) Que FK o Oracle REALMENTE declara para INSTRUMENTO_FINANCEIRO?
SELECT acc.column_name, accr.column_name AS coluna_pai
FROM all_constraints ac
JOIN all_cons_columns acc ON acc.owner=ac.owner AND acc.constraint_name=ac.constraint_name
JOIN all_constraints acr ON acr.owner=ac.r_owner AND acr.constraint_name=ac.r_constraint_name
JOIN all_cons_columns accr ON accr.owner=acr.owner AND accr.constraint_name=acr.constraint_name
                          AND accr.position=acc.position
WHERE ac.owner='CETIP' AND ac.table_name='HISTORICO_IF_TITULO'
  AND ac.constraint_type='R' AND acr.table_name='INSTRUMENTO_FINANCEIRO';

-- 3) NUM_IF_PERTENCE é usável? (é nullable no spec)
SELECT COUNT(*) total, COUNT(NUM_IF_PERTENCE) preenchidos FROM CETIP.HISTORICO_IF_TITULO;

-- Os CCBs que a query do produto seleciona (topo, NUM_IF_PERTENCE IS NULL)
-- têm histórico de título alcançável por esse vínculo?
SELECT COUNT(*)                          AS linhas_historico,
       COUNT(DISTINCT H.NUM_IF_PERTENCE) AS ccbs_com_historico
FROM   CETIP.HISTORICO_IF_TITULO H
JOIN   CETIP.INSTRUMENTO_FINANCEIRO I ON I.NUM_IF = H.NUM_IF_PERTENCE
WHERE  I.NUM_TIPO_IF = 53
  AND  I.NUM_IF_PERTENCE IS NULL
  AND  I.DAT_EXCLUSAO IS NULL;


-- LCI (75)
SELECT COUNT(*) AS rotas_elegiveis FROM CETIP.TIPO_OPER_OBJETO_SERV tos
 JOIN CETIP.TIPO_OPERACAO op ON op.NUM_ID_TIPO_OPERACAO = tos.NUM_ID_TIPO_OPERACAO
WHERE tos.NUM_ID_OBJETO_SERVICO = 75
  AND TRIM(op.COD_TIPO_OPERACAO) = '1' AND TRIM(tos.IND_DISPONIVEL_IDENTIFICACAO) = 'S';

-- LCA (843) — mesma query trocando 75 por 843
-- quantas LCIs teriam TODAS as operações em rota elegível?
SELECT COUNT(DISTINCT I.NUM_IF) FROM CETIP.INSTRUMENTO_FINANCEIRO I
WHERE I.NUM_TIPO_IF = 81 AND I.DAT_EXCLUSAO IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM CETIP.OPERACAO O
    WHERE O.NUM_IF = I.NUM_IF
      AND O.NUM_ID_TIPO_OPER_OBJETO_SERV NOT IN (
        SELECT tos.NUM_ID_TIPO_OPER_OBJETO_SERV FROM CETIP.TIPO_OPER_OBJETO_SERV tos
         JOIN CETIP.TIPO_OPERACAO op ON op.NUM_ID_TIPO_OPERACAO = tos.NUM_ID_TIPO_OPERACAO
        WHERE tos.NUM_ID_OBJETO_SERVICO = 75
          AND TRIM(op.COD_TIPO_OPERACAO) = '1'
          AND TRIM(tos.IND_DISPONIVEL_IDENTIFICACAO) = 'S'));

-- 1) O que é o lote 29277 no destino?
SELECT NUM_ID_LOTE, NUM_ID_TIPO_LOTE, NUM_CONTA_PARTICIPANTE, DAT_EXCLUSAO
FROM CETIP.LOTE WHERE NUM_ID_LOTE = 29277;

-- 2) Alguma LCI da origem usa esse lote?
SELECT COUNT(*) FROM CETIP.INSTRUMENTO_FINANCEIRO
WHERE NUM_TIPO_IF = 81 AND NUM_ID_LOTE = 29277 AND DAT_EXCLUSAO IS NULL;


-- Existe rota de registro aprovada no objeto 47?
SELECT COUNT(*) AS rotas_47 FROM CETIP.TIPO_OPER_OBJETO_SERV tos
 JOIN CETIP.TIPO_OPERACAO op ON op.NUM_ID_TIPO_OPERACAO = tos.NUM_ID_TIPO_OPERACAO
WHERE tos.NUM_ID_OBJETO_SERVICO = 47
  AND TRIM(op.COD_TIPO_OPERACAO) = '1' AND TRIM(tos.IND_DISPONIVEL_IDENTIFICACAO) = 'S';

-- Quantos CCBs (tipo 53) têm ao menos UMA operação nessa rota?
SELECT COUNT(DISTINCT I.NUM_IF) FROM CETIP.INSTRUMENTO_FINANCEIRO I
WHERE I.NUM_TIPO_IF = 53 AND I.DAT_EXCLUSAO IS NULL
  AND EXISTS (SELECT 1 FROM CETIP.OPERACAO O
              WHERE O.NUM_IF = I.NUM_IF
                AND O.NUM_ID_TIPO_OPER_OBJETO_SERV IN (
                  SELECT tos.NUM_ID_TIPO_OPER_OBJETO_SERV FROM CETIP.TIPO_OPER_OBJETO_SERV tos
                   JOIN CETIP.TIPO_OPERACAO op ON op.NUM_ID_TIPO_OPERACAO = tos.NUM_ID_TIPO_OPERACAO
                  WHERE tos.NUM_ID_OBJETO_SERVICO = 47
                    AND TRIM(op.COD_TIPO_OPERACAO) = '1'
                    AND TRIM(tos.IND_DISPONIVEL_IDENTIFICACAO) = 'S'));

1)
SELECT tos.NUM_ID_TIPO_OPER_OBJETO_SERV, tos.NUM_ID_OBJETO_SERVICO,
       op.COD_TIPO_OPERACAO, tos.IND_DISPONIVEL_IDENTIFICACAO
FROM   CETIP.TIPO_OPER_OBJETO_SERV tos
JOIN   CETIP.TIPO_OPERACAO op ON op.NUM_ID_TIPO_OPERACAO = tos.NUM_ID_TIPO_OPERACAO
WHERE  tos.NUM_ID_OBJETO_SERVICO = 1132
  AND  TRIM(op.COD_TIPO_OPERACAO) = '520';

20
SELECT /*+ PARALLEL(16) */
       COUNT(*)                                                    AS base_175,
       COUNT(CASE WHEN rota = 1 THEN 1 END)                        AS c1_rota_1132_520,
       COUNT(CASE WHEN grvm = 1 THEN 1 END)                        AS c2_if_grvm,
       COUNT(CASE WHEN ctr  = 1 THEN 1 END)                        AS c3_complemento_contrato,
       COUNT(CASE WHEN ppt  = 1 THEN 1 END)                        AS c4_parametro_ponta,
       COUNT(CASE WHEN aif  = 1 THEN 1 END)                        AS c5_arquivo_if,
       COUNT(CASE WHEN prt  = 1 THEN 1 END)                        AS c6_protocolo,
       COUNT(CASE WHEN oper = 1 THEN 1 END)                        AS c7_oper_com_dado_e_lanc,
       COUNT(CASE WHEN rota = 1 AND grvm = 1 AND ctr = 1 AND ppt = 1
                   AND aif = 1 AND prt = 1 AND oper = 1
                  THEN 1 END)                                      AS dominio_final
FROM (
  SELECT I.NUM_IF,
    CASE WHEN EXISTS (SELECT 1 FROM CETIP.OPERACAO O
                      JOIN CETIP.TIPO_OPER_OBJETO_SERV tos
                        ON tos.NUM_ID_TIPO_OPER_OBJETO_SERV = O.NUM_ID_TIPO_OPER_OBJETO_SERV
                      JOIN CETIP.TIPO_OPERACAO op
                        ON op.NUM_ID_TIPO_OPERACAO = tos.NUM_ID_TIPO_OPERACAO
                      WHERE O.NUM_IF = I.NUM_IF
                        AND tos.NUM_ID_OBJETO_SERVICO = 1132
                        AND TRIM(op.COD_TIPO_OPERACAO) = '520') THEN 1 ELSE 0 END AS rota,
    CASE WHEN EXISTS (SELECT 1 FROM CETIP.IF_GRVM              X WHERE X.NUM_IF = I.NUM_IF) THEN 1 ELSE 0 END AS grvm,
    CASE WHEN EXISTS (SELECT 1 FROM CETIP.COMPLEMENTO_CONTRATO X WHERE X.NUM_IF = I.NUM_IF) THEN 1 ELSE 0 END AS ctr,
    CASE WHEN EXISTS (SELECT 1 FROM CETIP.PARAMETRO_PONTA      X WHERE X.NUM_IF = I.NUM_IF) THEN 1 ELSE 0 END AS ppt,
    CASE WHEN EXISTS (SELECT 1 FROM CETIP.ARQUIVO_IF           X WHERE X.NUM_IF = I.NUM_IF) THEN 1 ELSE 0 END AS aif,
    CASE WHEN EXISTS (SELECT 1 FROM CETIP.PROTOCOLO            X WHERE X.NUM_IF = I.NUM_IF) THEN 1 ELSE 0 END AS prt,
    CASE WHEN EXISTS (SELECT 1 FROM CETIP.OPERACAO O
                      WHERE O.NUM_IF = I.NUM_IF
                        AND EXISTS (SELECT 1 FROM CETIP.DADO_OPERACAO D
                                    WHERE D.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO)
                        AND EXISTS (SELECT 1 FROM CETIP.LANCAMENTO L
                                    WHERE L.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO)) THEN 1 ELSE 0 END AS oper
  FROM CETIP.INSTRUMENTO_FINANCEIRO I
  WHERE I.NUM_TIPO_IF      = 175
    AND I.DAT_EXCLUSAO     IS NULL
    AND I.DAT_CANCELAMENTO IS NULL
);

-- 1) Quantos gravames têm QUALQUER operação? (a que eu deixei passar)
SELECT /*+ PARALLEL(16) */ COUNT(DISTINCT I.NUM_IF) AS com_qualquer_operacao
FROM   CETIP.INSTRUMENTO_FINANCEIRO I
WHERE  I.NUM_TIPO_IF = 175 AND I.DAT_EXCLUSAO IS NULL
  AND  EXISTS (SELECT 1 FROM CETIP.OPERACAO O WHERE O.NUM_IF = I.NUM_IF);

-- 2) Que rotas os gravames realmente usam?
SELECT /*+ PARALLEL(16) */ O.NUM_ID_TIPO_OPER_OBJETO_SERV AS rota,
       COUNT(DISTINCT O.NUM_IF) AS gravames, COUNT(*) AS operacoes
FROM   CETIP.OPERACAO O
JOIN   CETIP.INSTRUMENTO_FINANCEIRO I ON I.NUM_IF = O.NUM_IF
WHERE  I.NUM_TIPO_IF = 175 AND I.DAT_EXCLUSAO IS NULL
GROUP  BY O.NUM_ID_TIPO_OPER_OBJETO_SERV
ORDER  BY 2 DESC;

-- 3) Todas as rotas do objeto 1132 e seus códigos
SELECT tos.NUM_ID_TIPO_OPER_OBJETO_SERV AS rota, TRIM(op.COD_TIPO_OPERACAO) AS cod,
       op.NOM_TIPO_OPERACAO, tos.IND_DISPONIVEL_IDENTIFICACAO
FROM   CETIP.TIPO_OPER_OBJETO_SERV tos
JOIN   CETIP.TIPO_OPERACAO op ON op.NUM_ID_TIPO_OPERACAO = tos.NUM_ID_TIPO_OPERACAO
WHERE  tos.NUM_ID_OBJETO_SERVICO = 1132
ORDER  BY 2;


