SELECT COUNT(DISTINCT SCR.NUM_IF) FROM CETIP.CREDITO_SCR SCR
  JOIN CETIP.INSTRUMENTO_FINANCEIRO I ON I.NUM_IF = SCR.NUM_IF
 WHERE I.NUM_TIPO_IF = 81 AND SCR.DAT_EXCLUSAO IS NULL AND I.DAT_EXCLUSAO IS NULL;  -- LCI+lastro

SELECT COUNT(DISTINCT CDC.NUM_IF) FROM CETIP.CREDITO_DC CDC
  JOIN CETIP.INSTRUMENTO_FINANCEIRO I ON I.NUM_IF = CDC.NUM_IF
 WHERE I.NUM_TIPO_IF = 96 AND CDC.DAT_EXCLUSAO IS NULL AND I.DAT_EXCLUSAO IS NULL;  -- LCA+DC

SELECT NUM_TIPO_IF, COUNT(*) FROM CETIP.INSTRUMENTO_FINANCEIRO
 WHERE NUM_TIPO_IF IN (81,96) AND DAT_EXCLUSAO IS NULL GROUP BY NUM_TIPO_IF;        -- sanidade
