-- Spark SQL: contagens elegiveis segundo datagen/queries_produtos.sql.
-- Snapshot do catalogo local em 2026-09-10. Atualize junto com o catalogo.
-- Execute o setup uma vez; depois execute cada SELECT separadamente na mesma sessao.
-- OCI Data Science: use count_eligible_products.ipynb para executar via spark.sql().
-- Requer conector OCI e permissao de leitura no bucket.
-- Cada resultado conta NUM_IF distintos da query completa, sem LIMIT/amostragem.
-- Elegibilidade RAW nao substitui admissao no destino nem validacao do sintetico.
-- Os cenarios podem se sobrepor: nao some as contagens como um total unico.
-- Lastro/DICRE seguem o catalogo: NUM_IF nao nulos, nao total de masters SCR/DC.

-- SETUP: views temporarias sobre os Parquets exportados; nao copiam os dados.
CREATE OR REPLACE TEMPORARY VIEW RAW_INSTRUMENTO_FINANCEIRO
USING parquet OPTIONS (path 'oci://oci-st-blc-engordai-qab-n@gr97zovfhcmu/onprem-export-full/INSTRUMENTO_FINANCEIRO');
CREATE OR REPLACE TEMPORARY VIEW RAW_TITULO
USING parquet OPTIONS (path 'oci://oci-st-blc-engordai-qab-n@gr97zovfhcmu/onprem-export-full/TITULO');
CREATE OR REPLACE TEMPORARY VIEW RAW_CONDICAO_IF
USING parquet OPTIONS (path 'oci://oci-st-blc-engordai-qab-n@gr97zovfhcmu/onprem-export-full/CONDICAO_IF');
CREATE OR REPLACE TEMPORARY VIEW RAW_RESGATE
USING parquet OPTIONS (path 'oci://oci-st-blc-engordai-qab-n@gr97zovfhcmu/onprem-export-full/RESGATE');
CREATE OR REPLACE TEMPORARY VIEW RAW_DEPOSITO_AUTOMATICO_IF
USING parquet OPTIONS (path 'oci://oci-st-blc-engordai-qab-n@gr97zovfhcmu/onprem-export-full/DEPOSITO_AUTOMATICO_IF');
CREATE OR REPLACE TEMPORARY VIEW RAW_OPERACAO
USING parquet OPTIONS (path 'oci://oci-st-blc-engordai-qab-n@gr97zovfhcmu/onprem-export-full/OPERACAO');
CREATE OR REPLACE TEMPORARY VIEW RAW_TIPO_OPER_OBJETO_SERV
USING parquet OPTIONS (path 'oci://oci-st-blc-engordai-qab-n@gr97zovfhcmu/onprem-export-full/TIPO_OPER_OBJETO_SERV');
CREATE OR REPLACE TEMPORARY VIEW RAW_TIPO_OPERACAO
USING parquet OPTIONS (path 'oci://oci-st-blc-engordai-qab-n@gr97zovfhcmu/onprem-export-full/TIPO_OPERACAO');
CREATE OR REPLACE TEMPORARY VIEW RAW_DADO_OPERACAO
USING parquet OPTIONS (path 'oci://oci-st-blc-engordai-qab-n@gr97zovfhcmu/onprem-export-full/DADO_OPERACAO');
CREATE OR REPLACE TEMPORARY VIEW RAW_LANCAMENTO
USING parquet OPTIONS (path 'oci://oci-st-blc-engordai-qab-n@gr97zovfhcmu/onprem-export-full/LANCAMENTO');
CREATE OR REPLACE TEMPORARY VIEW RAW_ESPECIFICACAO
USING parquet OPTIONS (path 'oci://oci-st-blc-engordai-qab-n@gr97zovfhcmu/onprem-export-full/ESPECIFICACAO');
CREATE OR REPLACE TEMPORARY VIEW RAW_ESPECIFICACAO_COMITENTE
USING parquet OPTIONS (path 'oci://oci-st-blc-engordai-qab-n@gr97zovfhcmu/onprem-export-full/ESPECIFICACAO_COMITENTE');
CREATE OR REPLACE TEMPORARY VIEW RAW_LOTE
USING parquet OPTIONS (path 'oci://oci-st-blc-engordai-qab-n@gr97zovfhcmu/onprem-export-full/LOTE');
CREATE OR REPLACE TEMPORARY VIEW RAW_CREDITO_SCR
USING parquet OPTIONS (path 'oci://oci-st-blc-engordai-qab-n@gr97zovfhcmu/onprem-export-full/CREDITO_SCR');
CREATE OR REPLACE TEMPORARY VIEW RAW_HISTORICO_CREDITO_SCR
USING parquet OPTIONS (path 'oci://oci-st-blc-engordai-qab-n@gr97zovfhcmu/onprem-export-full/HISTORICO_CREDITO_SCR');
CREATE OR REPLACE TEMPORARY VIEW RAW_CARTEIRA_COMITENTE
USING parquet OPTIONS (path 'oci://oci-st-blc-engordai-qab-n@gr97zovfhcmu/onprem-export-full/CARTEIRA_COMITENTE');
CREATE OR REPLACE TEMPORARY VIEW RAW_CARTEIRA_PARTICIPANTE
USING parquet OPTIONS (path 'oci://oci-st-blc-engordai-qab-n@gr97zovfhcmu/onprem-export-full/CARTEIRA_PARTICIPANTE');
CREATE OR REPLACE TEMPORARY VIEW RAW_CREDITO_DC
USING parquet OPTIONS (path 'oci://oci-st-blc-engordai-qab-n@gr97zovfhcmu/onprem-export-full/CREDITO_DC');
CREATE OR REPLACE TEMPORARY VIEW RAW_FORMA_PAGAMENTO
USING parquet OPTIONS (path 'oci://oci-st-blc-engordai-qab-n@gr97zovfhcmu/onprem-export-full/FORMA_PAGAMENTO');
CREATE OR REPLACE TEMPORARY VIEW RAW_ACTPCCB_CONDICAO_IF
USING parquet OPTIONS (path 'oci://oci-st-blc-engordai-qab-n@gr97zovfhcmu/onprem-export-full/ACTPCCB_CONDICAO_IF');
CREATE OR REPLACE TEMPORARY VIEW RAW_COMPLEMENTO_CONTRATO
USING parquet OPTIONS (path 'oci://oci-st-blc-engordai-qab-n@gr97zovfhcmu/onprem-export-full/COMPLEMENTO_CONTRATO');

-- BEGIN COUNT: cdb_simplificado
SELECT 'cdb_simplificado' AS produto, COUNT(DISTINCT NUM_IF) AS qtd_elegiveis
FROM (
    WITH FILTRO_BASE AS (
        SELECT DISTINCT IFE.NUM_IF
        FROM RAW_INSTRUMENTO_FINANCEIRO IFE
        INNER JOIN RAW_TITULO TIT ON TIT.NUM_IF = IFE.NUM_IF
        INNER JOIN RAW_CONDICAO_IF CIF ON CIF.NUM_IF = IFE.NUM_IF
        INNER JOIN RAW_RESGATE RES ON RES.NUM_CONDICAO_IF = CIF.NUM_CONDICAO_IF
        WHERE IFE.NUM_TIPO_IF = 49
          AND TIT.COD_TIPO_ESCALONAMENTO IS NULL
          AND RES.COD_COND_RESGATE = 'SEM TABELA'
          AND IFE.DAT_EXCLUSAO IS NULL
          AND CIF.DAT_EXCLUSAO IS NULL
          AND RES.DAT_EXCLUSAO IS NULL
    ),
    FLAGS_IF AS (
        SELECT DISTINCT C.NUM_IF
        FROM RAW_CONDICAO_IF C
        INNER JOIN FILTRO_BASE FB ON FB.NUM_IF = C.NUM_IF
        WHERE C.DAT_EXCLUSAO IS NULL AND C.COD_TIPO_CONDICAO_IF <> 20
    ),
    DEP_IF AS (
        SELECT DISTINCT DP.NUM_IF
        FROM RAW_DEPOSITO_AUTOMATICO_IF DP
        INNER JOIN FILTRO_BASE FB ON FB.NUM_IF = DP.NUM_IF
        WHERE DP.NUM_IF IS NOT NULL
    ),
    OPER_REGISTRO AS (
        SELECT DISTINCT O.NUM_IF
        FROM RAW_OPERACAO O
        INNER JOIN RAW_TIPO_OPER_OBJETO_SERV TOS
            ON TOS.NUM_ID_TIPO_OPER_OBJETO_SERV = O.NUM_ID_TIPO_OPER_OBJETO_SERV
        INNER JOIN RAW_TIPO_OPERACAO TOP ON TOP.NUM_ID_TIPO_OPERACAO = TOS.NUM_ID_TIPO_OPERACAO
        WHERE TRIM(TOP.COD_TIPO_OPERACAO) = '1'
          AND TOS.NUM_ID_OBJETO_SERVICO = 44
          AND TRIM(TOS.IND_DISPONIVEL_IDENTIFICACAO) = 'S'
    )
    SELECT DISTINCT F.NUM_IF
    FROM FLAGS_IF F
    INNER JOIN DEP_IF DEP ON DEP.NUM_IF = F.NUM_IF
    INNER JOIN OPER_REGISTRO ORG ON ORG.NUM_IF = F.NUM_IF
    INNER JOIN RAW_OPERACAO O ON O.NUM_IF = F.NUM_IF
    INNER JOIN RAW_DADO_OPERACAO DOP ON DOP.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN RAW_LANCAMENTO LAN ON LAN.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN RAW_ESPECIFICACAO ESP ON ESP.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN RAW_ESPECIFICACAO_COMITENTE EPC ON EPC.NUM_ID_ESPECIFICACAO = ESP.NUM_ID_ESPECIFICACAO
) elegiveis;
-- END COUNT: cdb_simplificado

-- BEGIN COUNT: cdb_resgate
SELECT 'cdb_resgate' AS produto, COUNT(DISTINCT NUM_IF) AS qtd_elegiveis
FROM (
    WITH FILTRO_BASE AS (
        SELECT DISTINCT IFE.NUM_IF
        FROM RAW_INSTRUMENTO_FINANCEIRO IFE
        INNER JOIN RAW_TITULO TIT ON TIT.NUM_IF = IFE.NUM_IF
        INNER JOIN RAW_CONDICAO_IF CIF ON CIF.NUM_IF = IFE.NUM_IF
        INNER JOIN RAW_RESGATE RES ON RES.NUM_CONDICAO_IF = CIF.NUM_CONDICAO_IF
        INNER JOIN RAW_OPERACAO OPER ON OPER.NUM_IF = IFE.NUM_IF
        WHERE IFE.NUM_TIPO_IF = 49
          AND RES.COD_COND_RESGATE IN ('MERCADO', 'COM TABELA', 'ESPECIFICA')
          AND TIT.COD_TIPO_ESCALONAMENTO IS NULL
          AND IFE.DAT_EXCLUSAO IS NULL
          AND CIF.DAT_EXCLUSAO IS NULL
          AND RES.DAT_EXCLUSAO IS NULL
          AND TRY_CAST(TIT.QTD_RESGATADA AS DECIMAL(38, 18)) = 0
          AND OPER.COD_SITUACAO_OPERACAO = 43
          AND OPER.COD_CONTA_PARTE LIKE "%10-%"
          AND OPER.COD_CONTA_CONTRAPARTE LIKE "%40-%"
          AND OPER.NUM_ID_TIPO_OPER_OBJETO_SERV = 4509
    ),
    OPERACAO_FORA_ROTA AS (
        SELECT DISTINCT O.NUM_IF
        FROM RAW_OPERACAO O
        WHERE O.NUM_ID_TIPO_OPER_OBJETO_SERV IS NULL OR O.NUM_ID_TIPO_OPER_OBJETO_SERV <> 4509
    ),
    FLAGS_IF AS (
        SELECT DISTINCT C.NUM_IF
        FROM RAW_CONDICAO_IF C
        INNER JOIN FILTRO_BASE FB ON FB.NUM_IF = C.NUM_IF
        WHERE C.DAT_EXCLUSAO IS NULL AND C.COD_TIPO_CONDICAO_IF <> 20
    ),
    DEP_IF AS (
        SELECT DISTINCT DP.NUM_IF
        FROM RAW_DEPOSITO_AUTOMATICO_IF DP
        INNER JOIN FILTRO_BASE FB ON FB.NUM_IF = DP.NUM_IF
        WHERE DP.NUM_IF IS NOT NULL
    ),
    OPER_REGISTRO AS (
        SELECT DISTINCT O.NUM_IF
        FROM RAW_OPERACAO O
        INNER JOIN RAW_TIPO_OPER_OBJETO_SERV TOS
            ON TOS.NUM_ID_TIPO_OPER_OBJETO_SERV = O.NUM_ID_TIPO_OPER_OBJETO_SERV
        INNER JOIN RAW_TIPO_OPERACAO TOP ON TOP.NUM_ID_TIPO_OPERACAO = TOS.NUM_ID_TIPO_OPERACAO
        WHERE TRIM(TOP.COD_TIPO_OPERACAO) = '1'
          AND TOS.NUM_ID_OBJETO_SERVICO = 44
          AND TRIM(TOS.IND_DISPONIVEL_IDENTIFICACAO) = 'S'
    )
    SELECT DISTINCT F.NUM_IF
    FROM FLAGS_IF F
    INNER JOIN DEP_IF DEP ON DEP.NUM_IF = F.NUM_IF
    INNER JOIN OPER_REGISTRO ORG ON ORG.NUM_IF = F.NUM_IF
    LEFT ANTI JOIN OPERACAO_FORA_ROTA OFR ON OFR.NUM_IF = F.NUM_IF
    INNER JOIN RAW_OPERACAO O ON O.NUM_IF = F.NUM_IF
    INNER JOIN RAW_DADO_OPERACAO DOP ON DOP.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN RAW_LANCAMENTO LAN ON LAN.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN RAW_ESPECIFICACAO ESP ON ESP.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN RAW_ESPECIFICACAO_COMITENTE EPC ON EPC.NUM_ID_ESPECIFICACAO = ESP.NUM_ID_ESPECIFICACAO
) elegiveis;
-- END COUNT: cdb_resgate

-- BEGIN COUNT: cdb_escalonamento
SELECT 'cdb_escalonamento' AS produto, COUNT(DISTINCT NUM_IF) AS qtd_elegiveis
FROM (
    WITH FILTRO_BASE AS (
        SELECT DISTINCT IFE.NUM_IF
        FROM RAW_INSTRUMENTO_FINANCEIRO IFE
        INNER JOIN RAW_TITULO TIT ON TIT.NUM_IF = IFE.NUM_IF
        INNER JOIN RAW_CONDICAO_IF CIF ON CIF.NUM_IF = IFE.NUM_IF
        INNER JOIN RAW_RESGATE RES ON RES.NUM_CONDICAO_IF = CIF.NUM_CONDICAO_IF
        INNER JOIN RAW_OPERACAO OPER ON OPER.NUM_IF = IFE.NUM_IF
        WHERE IFE.NUM_TIPO_IF = 49
          AND RES.COD_COND_RESGATE IN ('SEM TABELA')
          AND TIT.COD_TIPO_ESCALONAMENTO IS NOT NULL
          AND TRY_CAST(TIT.QTD_RESGATADA AS DECIMAL(38, 18)) = 0
          AND IFE.DAT_EXCLUSAO IS NULL
          AND CIF.DAT_EXCLUSAO IS NULL
          AND RES.DAT_EXCLUSAO IS NULL
          AND OPER.COD_SITUACAO_OPERACAO = 43
          AND OPER.COD_CONTA_PARTE LIKE "%10-%"
          AND OPER.COD_CONTA_CONTRAPARTE LIKE "%40-%"
          AND OPER.NUM_ID_TIPO_OPER_OBJETO_SERV = 4509
    ),
    OPERACAO_FORA_ROTA AS (
        SELECT DISTINCT O.NUM_IF
        FROM RAW_OPERACAO O
        WHERE O.NUM_ID_TIPO_OPER_OBJETO_SERV IS NULL OR O.NUM_ID_TIPO_OPER_OBJETO_SERV <> 4509
    ),
    FLAGS_IF AS (
        SELECT DISTINCT C.NUM_IF
        FROM RAW_CONDICAO_IF C
        INNER JOIN FILTRO_BASE FB ON FB.NUM_IF = C.NUM_IF
        WHERE C.DAT_EXCLUSAO IS NULL AND C.COD_TIPO_CONDICAO_IF <> 20
    ),
    DEP_IF AS (
        SELECT DISTINCT DP.NUM_IF
        FROM RAW_DEPOSITO_AUTOMATICO_IF DP
        INNER JOIN FILTRO_BASE FB ON FB.NUM_IF = DP.NUM_IF
        WHERE DP.NUM_IF IS NOT NULL
    ),
    OPER_REGISTRO AS (
        SELECT DISTINCT O.NUM_IF
        FROM RAW_OPERACAO O
        INNER JOIN RAW_TIPO_OPER_OBJETO_SERV TOS
            ON TOS.NUM_ID_TIPO_OPER_OBJETO_SERV = O.NUM_ID_TIPO_OPER_OBJETO_SERV
        INNER JOIN RAW_TIPO_OPERACAO TOP ON TOP.NUM_ID_TIPO_OPERACAO = TOS.NUM_ID_TIPO_OPERACAO
        WHERE TRIM(TOP.COD_TIPO_OPERACAO) = '1'
          AND TOS.NUM_ID_OBJETO_SERVICO = 44
          AND TRIM(TOS.IND_DISPONIVEL_IDENTIFICACAO) = 'S'
    )
    SELECT DISTINCT F.NUM_IF
    FROM FLAGS_IF F
    INNER JOIN DEP_IF DEP ON DEP.NUM_IF = F.NUM_IF
    INNER JOIN OPER_REGISTRO ORG ON ORG.NUM_IF = F.NUM_IF
    LEFT ANTI JOIN OPERACAO_FORA_ROTA OFR ON OFR.NUM_IF = F.NUM_IF
    INNER JOIN RAW_OPERACAO O ON O.NUM_IF = F.NUM_IF
    INNER JOIN RAW_DADO_OPERACAO DOP ON DOP.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN RAW_LANCAMENTO LAN ON LAN.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN RAW_ESPECIFICACAO ESP ON ESP.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN RAW_ESPECIFICACAO_COMITENTE EPC ON EPC.NUM_ID_ESPECIFICACAO = ESP.NUM_ID_ESPECIFICACAO
) elegiveis;
-- END COUNT: cdb_escalonamento

-- BEGIN COUNT: rdb_inclusao
SELECT 'rdb_inclusao' AS produto, COUNT(DISTINCT NUM_IF) AS qtd_elegiveis
FROM (
    WITH FILTRO_BASE AS (
        SELECT DISTINCT IFE.NUM_IF
        FROM RAW_INSTRUMENTO_FINANCEIRO IFE
        INNER JOIN RAW_TITULO TIT ON TIT.NUM_IF = IFE.NUM_IF
        INNER JOIN RAW_CONDICAO_IF CIF ON CIF.NUM_IF = IFE.NUM_IF
        INNER JOIN RAW_RESGATE RES ON RES.NUM_CONDICAO_IF = CIF.NUM_CONDICAO_IF
        INNER JOIN RAW_OPERACAO OPER ON OPER.NUM_IF = IFE.NUM_IF
        WHERE IFE.NUM_TIPO_IF = 50
          AND RES.COD_COND_RESGATE IN ('SEM TABELA')
          AND TIT.COD_TIPO_ESCALONAMENTO IS NULL
          AND IFE.DAT_EXCLUSAO IS NULL
          AND CIF.DAT_EXCLUSAO IS NULL
          AND RES.DAT_EXCLUSAO IS NULL
          AND TIT.QTD_RESGATADA = 0
          AND OPER.COD_SITUACAO_OPERACAO = 43
          AND OPER.COD_CONTA_PARTE LIKE "%10-%"
          AND OPER.COD_CONTA_CONTRAPARTE LIKE "%40-%"
          AND OPER.NUM_ID_TIPO_OPER_OBJETO_SERV = 5177
    ),
    FLAGS_IF AS (
        SELECT DISTINCT C.NUM_IF
        FROM RAW_CONDICAO_IF C
        INNER JOIN FILTRO_BASE FB ON FB.NUM_IF = C.NUM_IF
        WHERE C.DAT_EXCLUSAO IS NULL AND C.COD_TIPO_CONDICAO_IF <> 20
    ),
    DEP_IF AS (
        SELECT DISTINCT DP.NUM_IF
        FROM RAW_DEPOSITO_AUTOMATICO_IF DP
        INNER JOIN FILTRO_BASE FB ON FB.NUM_IF = DP.NUM_IF
        WHERE DP.NUM_IF IS NOT NULL
    )
    SELECT DISTINCT F.NUM_IF
    FROM FLAGS_IF F
    INNER JOIN DEP_IF DEP ON DEP.NUM_IF = F.NUM_IF
    INNER JOIN RAW_OPERACAO O ON O.NUM_IF = F.NUM_IF
    INNER JOIN RAW_DADO_OPERACAO DOP ON DOP.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN RAW_LANCAMENTO LAN ON LAN.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN RAW_ESPECIFICACAO ESP ON ESP.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN RAW_ESPECIFICACAO_COMITENTE EPC ON EPC.NUM_ID_ESPECIFICACAO = ESP.NUM_ID_ESPECIFICACAO
) elegiveis;
-- END COUNT: rdb_inclusao

-- BEGIN COUNT: rdb_resgate
SELECT 'rdb_resgate' AS produto, COUNT(DISTINCT NUM_IF) AS qtd_elegiveis
FROM (
    WITH FILTRO_BASE AS (
        SELECT DISTINCT IFE.NUM_IF
        FROM RAW_INSTRUMENTO_FINANCEIRO IFE
        INNER JOIN RAW_TITULO TIT ON TIT.NUM_IF = IFE.NUM_IF
        INNER JOIN RAW_CONDICAO_IF CIF ON CIF.NUM_IF = IFE.NUM_IF
        INNER JOIN RAW_RESGATE RES ON RES.NUM_CONDICAO_IF = CIF.NUM_CONDICAO_IF
        INNER JOIN RAW_OPERACAO OPER ON OPER.NUM_IF = IFE.NUM_IF
        WHERE IFE.NUM_TIPO_IF = 50
          AND RES.COD_COND_RESGATE IN ('MERCADO', 'COM TABELA', 'ESPECIFICA')
          AND TIT.COD_TIPO_ESCALONAMENTO IS NULL
          AND IFE.DAT_EXCLUSAO IS NULL
          AND CIF.DAT_EXCLUSAO IS NULL
          AND RES.DAT_EXCLUSAO IS NULL
          AND TRY_CAST(TIT.QTD_RESGATADA AS DECIMAL(38, 18)) = 0
          AND OPER.COD_SITUACAO_OPERACAO = 43
          AND OPER.COD_CONTA_PARTE LIKE "%10-%"
          AND OPER.COD_CONTA_CONTRAPARTE LIKE "%40-%"
          AND OPER.NUM_ID_TIPO_OPER_OBJETO_SERV = 5177
    ),
    OPERACAO_FORA_ROTA AS (
        SELECT DISTINCT O.NUM_IF
        FROM RAW_OPERACAO O
        WHERE O.NUM_ID_TIPO_OPER_OBJETO_SERV IS NULL OR O.NUM_ID_TIPO_OPER_OBJETO_SERV <> 5177
    ),
    FLAGS_IF AS (
        SELECT DISTINCT C.NUM_IF
        FROM RAW_CONDICAO_IF C
        INNER JOIN FILTRO_BASE FB ON FB.NUM_IF = C.NUM_IF
        WHERE C.DAT_EXCLUSAO IS NULL AND C.COD_TIPO_CONDICAO_IF <> 20
    ),
    DEP_IF AS (
        SELECT DISTINCT DP.NUM_IF
        FROM RAW_DEPOSITO_AUTOMATICO_IF DP
        INNER JOIN FILTRO_BASE FB ON FB.NUM_IF = DP.NUM_IF
        WHERE DP.NUM_IF IS NOT NULL
    )
    SELECT DISTINCT F.NUM_IF
    FROM FLAGS_IF F
    INNER JOIN DEP_IF DEP ON DEP.NUM_IF = F.NUM_IF
    LEFT ANTI JOIN OPERACAO_FORA_ROTA OFR ON OFR.NUM_IF = F.NUM_IF
    INNER JOIN RAW_OPERACAO O ON O.NUM_IF = F.NUM_IF
    INNER JOIN RAW_DADO_OPERACAO DOP ON DOP.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN RAW_LANCAMENTO LAN ON LAN.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN RAW_ESPECIFICACAO ESP ON ESP.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN RAW_ESPECIFICACAO_COMITENTE EPC ON EPC.NUM_ID_ESPECIFICACAO = ESP.NUM_ID_ESPECIFICACAO
) elegiveis;
-- END COUNT: rdb_resgate

-- BEGIN COUNT: lci
SELECT 'lci' AS produto, COUNT(DISTINCT NUM_IF) AS qtd_elegiveis
FROM (
    WITH FILTRO_BASE AS (
        SELECT DISTINCT IFE.NUM_IF
        FROM RAW_INSTRUMENTO_FINANCEIRO IFE
        INNER JOIN RAW_TITULO TIT ON TIT.NUM_IF = IFE.NUM_IF
        INNER JOIN RAW_CONDICAO_IF CIF ON CIF.NUM_IF = IFE.NUM_IF
        INNER JOIN RAW_RESGATE RES ON RES.NUM_CONDICAO_IF = CIF.NUM_CONDICAO_IF
        INNER JOIN RAW_OPERACAO OPER ON OPER.NUM_IF = IFE.NUM_IF
        WHERE IFE.NUM_TIPO_IF = 81
          AND RES.COD_COND_RESGATE IN ('SEM TABELA')
          AND TIT.COD_TIPO_ESCALONAMENTO IS NULL
          AND IFE.DAT_EXCLUSAO IS NULL
          AND CIF.DAT_EXCLUSAO IS NULL
          AND RES.DAT_EXCLUSAO IS NULL
          AND OPER.COD_SITUACAO_OPERACAO = 43
          AND OPER.COD_CONTA_PARTE LIKE "%10-%"
          AND OPER.COD_CONTA_CONTRAPARTE LIKE "%40-%"
          AND OPER.NUM_ID_TIPO_OPER_OBJETO_SERV = 3949
    ),
    FLAGS_IF AS (
        SELECT DISTINCT C.NUM_IF
        FROM RAW_CONDICAO_IF C
        INNER JOIN FILTRO_BASE FB ON FB.NUM_IF = C.NUM_IF
        WHERE C.DAT_EXCLUSAO IS NULL AND C.COD_TIPO_CONDICAO_IF <> 20
    ),
    DEP_IF AS (
        SELECT DISTINCT DP.NUM_IF
        FROM RAW_DEPOSITO_AUTOMATICO_IF DP
        INNER JOIN FILTRO_BASE FB ON FB.NUM_IF = DP.NUM_IF
        WHERE DP.NUM_IF IS NOT NULL
    ),
    ROTA_ELEGIVEL AS (
        SELECT DISTINCT TOS.NUM_ID_TIPO_OPER_OBJETO_SERV
        FROM RAW_TIPO_OPER_OBJETO_SERV TOS
        INNER JOIN RAW_TIPO_OPERACAO TOP ON TOP.NUM_ID_TIPO_OPERACAO = TOS.NUM_ID_TIPO_OPERACAO
        WHERE TOS.NUM_ID_OBJETO_SERVICO = 75
          AND TRIM(TOP.COD_TIPO_OPERACAO) = '1'
          AND TRIM(TOS.IND_DISPONIVEL_IDENTIFICACAO) = 'S'
    ),
    ROTA_INVALIDA AS (
        SELECT DISTINCT O.NUM_IF
        FROM RAW_OPERACAO O
        LEFT JOIN ROTA_ELEGIVEL RE ON RE.NUM_ID_TIPO_OPER_OBJETO_SERV = O.NUM_ID_TIPO_OPER_OBJETO_SERV
        WHERE RE.NUM_ID_TIPO_OPER_OBJETO_SERV IS NULL
    ),
    LOTE_ELEGIVEL AS (
        SELECT DISTINCT L.NUM_ID_LOTE
        FROM RAW_LOTE L
        WHERE L.NUM_ID_TIPO_LOTE = 1 AND L.NUM_CONTA_PARTICIPANTE IS NOT NULL
    ),
    LOTE_COM_LASTRO AS (
        SELECT DISTINCT S.NUM_ID_LOTE
        FROM RAW_CREDITO_SCR S
        INNER JOIN RAW_HISTORICO_CREDITO_SCR H ON H.NUM_ID_CREDITO_SCR = S.NUM_ID_CREDITO_SCR
        WHERE S.DAT_EXCLUSAO IS NULL AND S.NUM_ID_LOTE IS NOT NULL
    ),
    CARTEIRA_DUPLICADA AS (
        SELECT DISTINCT NUM_IF FROM (
            SELECT CC.NUM_IF
            FROM RAW_CARTEIRA_COMITENTE CC
            GROUP BY CC.NUM_IF, CC.NUM_ID_ENTIDADE, CC.COD_TIPO_POSICAO_CARTEIRA,
                     CC.NUM_SISTEMA, CC.NUM_CONTA_PARTICIPANTE
            HAVING COUNT(*) > 1
            UNION ALL
            SELECT CP.NUM_IF
            FROM RAW_CARTEIRA_PARTICIPANTE CP
            GROUP BY CP.NUM_IF, CP.COD_TIPO_POSICAO_CARTEIRA, CP.NUM_SISTEMA, CP.NUM_CONTA_PARTICIPANTE
            HAVING COUNT(*) > 1
        ) D
    )
    SELECT DISTINCT F.NUM_IF
    FROM FLAGS_IF F
    INNER JOIN DEP_IF DEP ON DEP.NUM_IF = F.NUM_IF
    INNER JOIN RAW_INSTRUMENTO_FINANCEIRO IFL ON IFL.NUM_IF = F.NUM_IF
    INNER JOIN LOTE_ELEGIVEL LE ON LE.NUM_ID_LOTE = IFL.NUM_ID_LOTE
    INNER JOIN LOTE_COM_LASTRO LCL ON LCL.NUM_ID_LOTE = IFL.NUM_ID_LOTE
    LEFT ANTI JOIN ROTA_INVALIDA RI ON RI.NUM_IF = F.NUM_IF
    LEFT ANTI JOIN CARTEIRA_DUPLICADA CD ON CD.NUM_IF = F.NUM_IF
    INNER JOIN RAW_OPERACAO O ON O.NUM_IF = F.NUM_IF
    INNER JOIN RAW_DADO_OPERACAO DOP ON DOP.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN RAW_LANCAMENTO LAN ON LAN.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN RAW_ESPECIFICACAO ESP ON ESP.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN RAW_ESPECIFICACAO_COMITENTE EPC ON EPC.NUM_ID_ESPECIFICACAO = ESP.NUM_ID_ESPECIFICACAO
) elegiveis;
-- END COUNT: lci

-- BEGIN COUNT: lca
SELECT 'lca' AS produto, COUNT(DISTINCT NUM_IF) AS qtd_elegiveis
FROM (
    WITH FILTRO_BASE AS (
        SELECT DISTINCT IFE.NUM_IF
        FROM RAW_INSTRUMENTO_FINANCEIRO IFE
        INNER JOIN RAW_TITULO TIT ON TIT.NUM_IF = IFE.NUM_IF
        INNER JOIN RAW_CONDICAO_IF CIF ON CIF.NUM_IF = IFE.NUM_IF
        INNER JOIN RAW_RESGATE RES ON RES.NUM_CONDICAO_IF = CIF.NUM_CONDICAO_IF
        INNER JOIN RAW_OPERACAO OPER ON OPER.NUM_IF = IFE.NUM_IF
        WHERE IFE.NUM_TIPO_IF = 96
          AND RES.COD_COND_RESGATE IN ('SEM TABELA')
          AND TIT.COD_TIPO_ESCALONAMENTO IS NULL
          AND IFE.DAT_EXCLUSAO IS NULL
          AND CIF.DAT_EXCLUSAO IS NULL
          AND RES.DAT_EXCLUSAO IS NULL
          AND OPER.COD_SITUACAO_OPERACAO = 43
          AND OPER.COD_CONTA_PARTE LIKE "%10-%"
          AND OPER.COD_CONTA_CONTRAPARTE LIKE "%40-%"
          AND OPER.NUM_ID_TIPO_OPER_OBJETO_SERV = 3858
    ),
    FLAGS_IF AS (
        SELECT DISTINCT C.NUM_IF
        FROM RAW_CONDICAO_IF C
        INNER JOIN FILTRO_BASE FB ON FB.NUM_IF = C.NUM_IF
        WHERE C.DAT_EXCLUSAO IS NULL AND C.COD_TIPO_CONDICAO_IF <> 20
    ),
    DEP_IF AS (
        SELECT DISTINCT DP.NUM_IF
        FROM RAW_DEPOSITO_AUTOMATICO_IF DP
        INNER JOIN FILTRO_BASE FB ON FB.NUM_IF = DP.NUM_IF
        WHERE DP.NUM_IF IS NOT NULL
    ),
    ROTA_ELEGIVEL AS (
        SELECT DISTINCT TOS.NUM_ID_TIPO_OPER_OBJETO_SERV
        FROM RAW_TIPO_OPER_OBJETO_SERV TOS
        INNER JOIN RAW_TIPO_OPERACAO TOP ON TOP.NUM_ID_TIPO_OPERACAO = TOS.NUM_ID_TIPO_OPERACAO
        WHERE TOS.NUM_ID_OBJETO_SERVICO = 843
          AND TRIM(TOP.COD_TIPO_OPERACAO) = '1'
          AND TRIM(TOS.IND_DISPONIVEL_IDENTIFICACAO) = 'S'
    ),
    ROTA_INVALIDA AS (
        SELECT DISTINCT O.NUM_IF
        FROM RAW_OPERACAO O
        LEFT JOIN ROTA_ELEGIVEL RE ON RE.NUM_ID_TIPO_OPER_OBJETO_SERV = O.NUM_ID_TIPO_OPER_OBJETO_SERV
        WHERE RE.NUM_ID_TIPO_OPER_OBJETO_SERV IS NULL
    ),
    LOTE_ELEGIVEL AS (
        SELECT DISTINCT L.NUM_ID_LOTE
        FROM RAW_LOTE L
        WHERE L.NUM_ID_TIPO_LOTE = 2 AND L.NUM_CONTA_PARTICIPANTE IS NOT NULL
    ),
    LOTE_COM_DC AS (
        SELECT DISTINCT S.NUM_ID_LOTE
        FROM RAW_CREDITO_DC S
        WHERE S.DAT_EXCLUSAO IS NULL AND S.NUM_ID_LOTE IS NOT NULL
    ),
    CARTEIRA_DUPLICADA AS (
        SELECT DISTINCT NUM_IF FROM (
            SELECT CC.NUM_IF
            FROM RAW_CARTEIRA_COMITENTE CC
            GROUP BY CC.NUM_IF, CC.NUM_ID_ENTIDADE, CC.COD_TIPO_POSICAO_CARTEIRA,
                     CC.NUM_SISTEMA, CC.NUM_CONTA_PARTICIPANTE
            HAVING COUNT(*) > 1
            UNION ALL
            SELECT CP.NUM_IF
            FROM RAW_CARTEIRA_PARTICIPANTE CP
            GROUP BY CP.NUM_IF, CP.COD_TIPO_POSICAO_CARTEIRA, CP.NUM_SISTEMA, CP.NUM_CONTA_PARTICIPANTE
            HAVING COUNT(*) > 1
        ) D
    )
    SELECT DISTINCT F.NUM_IF
    FROM FLAGS_IF F
    INNER JOIN DEP_IF DEP ON DEP.NUM_IF = F.NUM_IF
    INNER JOIN RAW_INSTRUMENTO_FINANCEIRO IFL ON IFL.NUM_IF = F.NUM_IF
    INNER JOIN LOTE_ELEGIVEL LE ON LE.NUM_ID_LOTE = IFL.NUM_ID_LOTE
    INNER JOIN LOTE_COM_DC LCD ON LCD.NUM_ID_LOTE = IFL.NUM_ID_LOTE
    LEFT ANTI JOIN ROTA_INVALIDA RI ON RI.NUM_IF = F.NUM_IF
    LEFT ANTI JOIN CARTEIRA_DUPLICADA CD ON CD.NUM_IF = F.NUM_IF
    INNER JOIN RAW_OPERACAO O ON O.NUM_IF = F.NUM_IF
    INNER JOIN RAW_DADO_OPERACAO DOP ON DOP.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN RAW_LANCAMENTO LAN ON LAN.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN RAW_ESPECIFICACAO ESP ON ESP.NUM_ID_OPERACAO = O.NUM_ID_OPERACAO
    INNER JOIN RAW_ESPECIFICACAO_COMITENTE EPC ON EPC.NUM_ID_ESPECIFICACAO = ESP.NUM_ID_ESPECIFICACAO
) elegiveis;
-- END COUNT: lca

-- BEGIN COUNT: ccb_pppre
SELECT 'ccb_pppre' AS produto, COUNT(DISTINCT NUM_IF) AS qtd_elegiveis
FROM (
    WITH OPER_REGISTRO AS (
        SELECT DISTINCT O.NUM_IF
        FROM RAW_OPERACAO O
        INNER JOIN RAW_TIPO_OPER_OBJETO_SERV TOS
            ON TOS.NUM_ID_TIPO_OPER_OBJETO_SERV = O.NUM_ID_TIPO_OPER_OBJETO_SERV
        INNER JOIN RAW_TIPO_OPERACAO TOP ON TOP.NUM_ID_TIPO_OPERACAO = TOS.NUM_ID_TIPO_OPERACAO
        WHERE TOS.NUM_ID_OBJETO_SERVICO = 47
          AND TRIM(TOP.COD_TIPO_OPERACAO) = '1'
          AND TRIM(TOS.IND_DISPONIVEL_IDENTIFICACAO) = 'S'
          AND O.COD_SITUACAO_OPERACAO = 43
          AND O.COD_CONTA_PARTE LIKE "%00-%"
          AND O.COD_CONTA_CONTRAPARTE LIKE "%40-%"
          AND O.NUM_ID_TIPO_OPER_OBJETO_SERV = 871
    ),
    OPERACAO_INVALIDA AS (
        SELECT DISTINCT O.NUM_IF
        FROM RAW_OPERACAO O
        WHERE O.NUM_ID_TIPO_OPER_OBJETO_SERV IS NULL
           OR O.NUM_ID_TIPO_OPER_OBJETO_SERV <> 871
           OR O.COD_SITUACAO_OPERACAO IS NULL
           OR O.COD_SITUACAO_OPERACAO <> 43
    )
    SELECT DISTINCT I.NUM_IF
    FROM RAW_INSTRUMENTO_FINANCEIRO I
    INNER JOIN RAW_FORMA_PAGAMENTO FP ON FP.NUM_ID_FORMA_PAGAMENTO = I.NUM_ID_FORMA_PAGAMENTO
    INNER JOIN RAW_ACTPCCB_CONDICAO_IF ACIF ON ACIF.NUM_IF = I.NUM_IF
    INNER JOIN OPER_REGISTRO ORG ON ORG.NUM_IF = I.NUM_IF
    LEFT ANTI JOIN OPERACAO_INVALIDA OI ON OI.NUM_IF = I.NUM_IF
    WHERE I.NUM_TIPO_IF = 53
      AND I.NUM_IF_PERTENCE IS NULL
      AND I.DAT_EXCLUSAO IS NULL
      AND UPPER(TRIM(ACIF.RENT_INDEXADOR_TAXA_FLU)) = 'PREFIXADO'
      AND UPPER(TRIM(ACIF.FORMA_PAGAMENTO)) = 'PAGAMENTO DE PARCELAS'
) elegiveis;
-- END COUNT: ccb_pppre

-- BEGIN COUNT: ccb_pfpre
SELECT 'ccb_pfpre' AS produto, COUNT(DISTINCT NUM_IF) AS qtd_elegiveis
FROM (
    WITH OPER_REGISTRO AS (
        SELECT DISTINCT O.NUM_IF
        FROM RAW_OPERACAO O
        INNER JOIN RAW_TIPO_OPER_OBJETO_SERV TOS
            ON TOS.NUM_ID_TIPO_OPER_OBJETO_SERV = O.NUM_ID_TIPO_OPER_OBJETO_SERV
        INNER JOIN RAW_TIPO_OPERACAO TOP ON TOP.NUM_ID_TIPO_OPERACAO = TOS.NUM_ID_TIPO_OPERACAO
        WHERE TOS.NUM_ID_OBJETO_SERVICO = 47
          AND TRIM(TOP.COD_TIPO_OPERACAO) = '1'
          AND TRIM(TOS.IND_DISPONIVEL_IDENTIFICACAO) = 'S'
          AND O.COD_SITUACAO_OPERACAO = 43
          AND O.COD_CONTA_PARTE LIKE "%00-%"
          AND O.COD_CONTA_CONTRAPARTE LIKE "%40-%"
          AND O.NUM_ID_TIPO_OPER_OBJETO_SERV = 871
    ),
    OPERACAO_FORA_ROTA AS (
        SELECT DISTINCT O.NUM_IF
        FROM RAW_OPERACAO O
        WHERE O.NUM_ID_TIPO_OPER_OBJETO_SERV IS NULL OR O.NUM_ID_TIPO_OPER_OBJETO_SERV <> 871
    )
    SELECT DISTINCT I.NUM_IF
    FROM RAW_INSTRUMENTO_FINANCEIRO I
    INNER JOIN RAW_FORMA_PAGAMENTO FP ON FP.NUM_ID_FORMA_PAGAMENTO = I.NUM_ID_FORMA_PAGAMENTO
    INNER JOIN RAW_ACTPCCB_CONDICAO_IF ACIF ON ACIF.NUM_IF = I.NUM_IF
    INNER JOIN OPER_REGISTRO ORG ON ORG.NUM_IF = I.NUM_IF
    LEFT ANTI JOIN OPERACAO_FORA_ROTA OFR ON OFR.NUM_IF = I.NUM_IF
    WHERE I.NUM_TIPO_IF = 53
      AND I.NUM_IF_PERTENCE IS NULL
      AND I.DAT_EXCLUSAO IS NULL
      AND UPPER(TRIM(ACIF.RENT_INDEXADOR_TAXA_FLU)) = 'PREFIXADO'
      AND UPPER(TRIM(ACIF.FORMA_PAGAMENTO)) = 'PAGAMENTO DE PARCELAS FIXAS'
) elegiveis;
-- END COUNT: ccb_pfpre

-- BEGIN COUNT: ccb_pgrpre
SELECT 'ccb_pgrpre' AS produto, COUNT(DISTINCT NUM_IF) AS qtd_elegiveis
FROM (
    WITH OPER_REGISTRO AS (
        SELECT DISTINCT O.NUM_IF
        FROM RAW_OPERACAO O
        INNER JOIN RAW_TIPO_OPER_OBJETO_SERV TOS
            ON TOS.NUM_ID_TIPO_OPER_OBJETO_SERV = O.NUM_ID_TIPO_OPER_OBJETO_SERV
        INNER JOIN RAW_TIPO_OPERACAO TOP ON TOP.NUM_ID_TIPO_OPERACAO = TOS.NUM_ID_TIPO_OPERACAO
        WHERE TOS.NUM_ID_OBJETO_SERVICO = 47
          AND TRIM(TOP.COD_TIPO_OPERACAO) = '1'
          AND TRIM(TOS.IND_DISPONIVEL_IDENTIFICACAO) = 'S'
          AND O.COD_SITUACAO_OPERACAO = 43
          AND O.COD_CONTA_PARTE LIKE "%00-%"
          AND O.COD_CONTA_CONTRAPARTE LIKE "%40-%"
          AND O.NUM_ID_TIPO_OPER_OBJETO_SERV = 871
    )
    SELECT DISTINCT I.NUM_IF
    FROM RAW_INSTRUMENTO_FINANCEIRO I
    INNER JOIN RAW_FORMA_PAGAMENTO FP ON FP.NUM_ID_FORMA_PAGAMENTO = I.NUM_ID_FORMA_PAGAMENTO
    INNER JOIN RAW_ACTPCCB_CONDICAO_IF ACIF ON ACIF.NUM_IF = I.NUM_IF
    INNER JOIN OPER_REGISTRO ORG ON ORG.NUM_IF = I.NUM_IF
    WHERE I.NUM_TIPO_IF = 53
      AND I.NUM_IF_PERTENCE IS NULL
      AND I.DAT_EXCLUSAO IS NULL
      AND UPPER(TRIM(ACIF.RENT_INDEXADOR_TAXA_FLU)) = 'VCP'
      AND UPPER(TRIM(ACIF.FORMA_PAGAMENTO)) = 'PAGAMENTO DE RENDIMENTO PREFIXADO'
) elegiveis;
-- END COUNT: ccb_pgrpre

-- BEGIN COUNT: ccb_favcp
SELECT 'ccb_favcp' AS produto, COUNT(DISTINCT NUM_IF) AS qtd_elegiveis
FROM (
    WITH OPER_REGISTRO AS (
        SELECT DISTINCT O.NUM_IF
        FROM RAW_OPERACAO O
        INNER JOIN RAW_TIPO_OPER_OBJETO_SERV TOS
            ON TOS.NUM_ID_TIPO_OPER_OBJETO_SERV = O.NUM_ID_TIPO_OPER_OBJETO_SERV
        INNER JOIN RAW_TIPO_OPERACAO TOP ON TOP.NUM_ID_TIPO_OPERACAO = TOS.NUM_ID_TIPO_OPERACAO
        WHERE TOS.NUM_ID_OBJETO_SERVICO = 47
          AND TRIM(TOP.COD_TIPO_OPERACAO) = '1'
          AND TRIM(TOS.IND_DISPONIVEL_IDENTIFICACAO) = 'S'
          AND O.COD_SITUACAO_OPERACAO = 43
          AND O.COD_CONTA_PARTE LIKE "%00-%"
          AND O.COD_CONTA_CONTRAPARTE LIKE "%40-%"
          AND O.NUM_ID_TIPO_OPER_OBJETO_SERV = 871
    ),
    OPERACAO_FORA_ROTA AS (
        SELECT DISTINCT O.NUM_IF
        FROM RAW_OPERACAO O
        WHERE O.NUM_ID_TIPO_OPER_OBJETO_SERV IS NULL OR O.NUM_ID_TIPO_OPER_OBJETO_SERV <> 871
    )
    SELECT DISTINCT I.NUM_IF
    FROM RAW_INSTRUMENTO_FINANCEIRO I
    INNER JOIN RAW_FORMA_PAGAMENTO FP ON FP.NUM_ID_FORMA_PAGAMENTO = I.NUM_ID_FORMA_PAGAMENTO
    INNER JOIN RAW_ACTPCCB_CONDICAO_IF ACIF ON ACIF.NUM_IF = I.NUM_IF
    INNER JOIN OPER_REGISTRO ORG ON ORG.NUM_IF = I.NUM_IF
    LEFT ANTI JOIN OPERACAO_FORA_ROTA OFR ON OFR.NUM_IF = I.NUM_IF
    WHERE I.NUM_TIPO_IF = 53
      AND I.NUM_IF_PERTENCE IS NULL
      AND I.DAT_EXCLUSAO IS NULL
      AND UPPER(TRIM(ACIF.RENT_INDEXADOR_TAXA_FLU)) = 'VCP'
      AND UPPER(TRIM(ACIF.FORMA_PAGAMENTO)) = 'LIQUIDAÇÃO FORA DO ÂMBITO B3'
) elegiveis;
-- END COUNT: ccb_favcp

-- BEGIN COUNT: ccb_fapre
SELECT 'ccb_fapre' AS produto, COUNT(DISTINCT NUM_IF) AS qtd_elegiveis
FROM (
    WITH OPER_REGISTRO AS (
        SELECT DISTINCT O.NUM_IF
        FROM RAW_OPERACAO O
        INNER JOIN RAW_TIPO_OPER_OBJETO_SERV TOS
            ON TOS.NUM_ID_TIPO_OPER_OBJETO_SERV = O.NUM_ID_TIPO_OPER_OBJETO_SERV
        INNER JOIN RAW_TIPO_OPERACAO TOP ON TOP.NUM_ID_TIPO_OPERACAO = TOS.NUM_ID_TIPO_OPERACAO
        WHERE TOS.NUM_ID_OBJETO_SERVICO = 47
          AND TRIM(TOP.COD_TIPO_OPERACAO) = '1'
          AND TRIM(TOS.IND_DISPONIVEL_IDENTIFICACAO) = 'S'
          AND O.COD_SITUACAO_OPERACAO = 43
          AND O.COD_CONTA_PARTE LIKE "%00-%"
          AND O.COD_CONTA_CONTRAPARTE LIKE "%40-%"
          AND O.NUM_ID_TIPO_OPER_OBJETO_SERV = 871
    )
    SELECT DISTINCT I.NUM_IF
    FROM RAW_INSTRUMENTO_FINANCEIRO I
    INNER JOIN RAW_FORMA_PAGAMENTO FP ON FP.NUM_ID_FORMA_PAGAMENTO = I.NUM_ID_FORMA_PAGAMENTO
    INNER JOIN RAW_ACTPCCB_CONDICAO_IF ACIF ON ACIF.NUM_IF = I.NUM_IF
    INNER JOIN OPER_REGISTRO ORG ON ORG.NUM_IF = I.NUM_IF
    WHERE I.NUM_TIPO_IF = 53
      AND I.NUM_IF_PERTENCE IS NULL
      AND I.DAT_EXCLUSAO IS NULL
      AND UPPER(TRIM(ACIF.RENT_INDEXADOR_TAXA_FLU)) = 'PREFIXADO'
      AND UPPER(TRIM(ACIF.FORMA_PAGAMENTO)) = 'LIQUIDAÇÃO FORA DO ÂMBITO B3'
) elegiveis;
-- END COUNT: ccb_fapre

-- BEGIN COUNT: gravame
SELECT 'gravame' AS produto, COUNT(DISTINCT NUM_IF) AS qtd_elegiveis
FROM (
    WITH FILTRO_BASE AS (
        SELECT DISTINCT IFE.NUM_IF
        FROM RAW_INSTRUMENTO_FINANCEIRO IFE
        INNER JOIN RAW_COMPLEMENTO_CONTRATO CT ON CT.NUM_IF = IFE.NUM_IF
        INNER JOIN RAW_OPERACAO OPER ON OPER.NUM_IF = IFE.NUM_IF
        WHERE IFE.NUM_TIPO_IF = 175
          AND IFE.DAT_EXCLUSAO IS NULL
          AND CT.DAT_EXCLUSAO IS NULL
          AND OPER.COD_SITUACAO_OPERACAO = 43
          AND OPER.COD_CONTA_PARTE LIKE "%00-%"
          AND OPER.COD_CONTA_CONTRAPARTE LIKE "%10-%"
          AND OPER.NUM_ID_TIPO_OPER_OBJETO_SERV IN (15394, 15512)
    ),
    OPER_REGISTRO AS (
        SELECT DISTINCT O.NUM_IF
        FROM RAW_OPERACAO O
        INNER JOIN RAW_TIPO_OPER_OBJETO_SERV TOS
            ON TOS.NUM_ID_TIPO_OPER_OBJETO_SERV = O.NUM_ID_TIPO_OPER_OBJETO_SERV
        INNER JOIN RAW_TIPO_OPERACAO TOP ON TOP.NUM_ID_TIPO_OPERACAO = TOS.NUM_ID_TIPO_OPERACAO
        WHERE TOS.NUM_ID_OBJETO_SERVICO = 1132
          AND TRIM(TOP.COD_TIPO_OPERACAO) IN ('520', '527')
    ),
    OPERACAO_FORA_ROTA AS (
        SELECT DISTINCT O.NUM_IF
        FROM RAW_OPERACAO O
        WHERE O.NUM_ID_TIPO_OPER_OBJETO_SERV IS NULL
           OR O.NUM_ID_TIPO_OPER_OBJETO_SERV NOT IN (15394, 15512)
    )
    SELECT DISTINCT F.NUM_IF
    FROM FILTRO_BASE F
    INNER JOIN OPER_REGISTRO ORG ON ORG.NUM_IF = F.NUM_IF
    LEFT ANTI JOIN OPERACAO_FORA_ROTA OFR ON OFR.NUM_IF = F.NUM_IF
) elegiveis;
-- END COUNT: gravame

-- BEGIN COUNT: lastro
SELECT 'lastro' AS produto, COUNT(DISTINCT NUM_IF) AS qtd_elegiveis
FROM (
    SELECT DISTINCT SCR.NUM_IF
    FROM RAW_CREDITO_SCR SCR
    WHERE SCR.DAT_EXCLUSAO IS NULL AND SCR.NUM_IF IS NOT NULL
) elegiveis;
-- END COUNT: lastro

-- BEGIN COUNT: direito_creditorio
SELECT 'direito_creditorio' AS produto, COUNT(DISTINCT NUM_IF) AS qtd_elegiveis
FROM (
    SELECT DISTINCT CDC.NUM_IF
    FROM RAW_CREDITO_DC CDC
    WHERE CDC.DAT_EXCLUSAO IS NULL AND CDC.NUM_IF IS NOT NULL
) elegiveis;
-- END COUNT: direito_creditorio
