SELECT /*+ PARALLEL(16) */
COUNT(DISTINCT IFE.NUM_IF) IFE, COUNT(DISTINCT TIT.NUM_IF) TITULO,
COUNT(DISTINCT CRE.NUM_IF) CRE, COUNT(DISTINCT CIF.NUM_CONDICAO_IF) CIF,
COUNT(DISTINCT RES.NUM_CONDICAO_IF) RES, COUNT(DISTINCT JFL.NUM_CONDICAO_IF) JFL,
--COUNT(DISTINCT JFI.NUM_CONDICAO_IF) JFI,
COUNT(DISTINCT EVE.NUM_EVENTO) EVE
FROM CETIP.INSTRUMENTO_FINANCEIRO ifE,
CETIP.TITULO tIT,
CETIP.CREDITO CRE,
CETIP.CONDICAO_IF ciF,
CETIP.RESGATE res,
CETIP.JUROS_FLUTUANTE jfL,
--CETIP.JUROS_FIXO jfI,
CETIP.EVENTO EVE
WHERE ifE.NUM_TIPO_IF = 49
AND IFE.NUM_IF IN (2174178447)--,2175921807)
AND ifE.DAT_EXCLUSAO IS NULL
AND IFE.NUM_IF = TIT.NUM_IF
AND IFE.NUM_IF = CRE.NUM_IF
AND IFE.NUM_IF = ciF.NUM_IF
AND IFE.NUM_IF = EVE.NUM_IF
AND (res.COD_COND_RESGATE in ('SEM TABELA') OR
res.COD_COND_RESGATE IS null)
and ciF.NUM_CONDICAO_IF = res.NUM_CONDICAO_IF(+)
AND CIF.NUM_CONDICAO_IF = JFL.NUM_CONDICAO_IF(+)
--AND CIF.NUM_CONDICAO_IF = JFI.NUM_CONDICAO_IF(+)
AND TIT.COD_TIPO_ESCALONAMENTO IS NULL
AND ciF.DAT_EXCLUSAO IS NULL
AND EVE.DAT_EXCLUSAO IS NULL